[formatting]
  align_entries = true

  array_auto_collapse = false
  compact_arrays      = false

  indent_entries      = true
  indent_tables       = true
  inline_table_expand = true

  reorder_arrays        = true
  reorder_inline_tables = true
  reorder_keys          = true
